export enum ProjectActionTypes {
  CREATE_PROJECT = "CREATE_PROJECT",
  PROJECT_SUCCESSFUL_CREATED = "PROJECT_SUCCESSFUL_CREATED",
  PROJECT_FAILED_CREATED = "PROJECT_FAILED_CREATED",
  FETCH_USER_PROJECTS = "FETCH_USER_PROJECTS",
  SET_USER_PROJECTS = "SET_USER_PROJECTS",
}
