export enum TusksActionTypes {
  SET_TUSKS = "SET_TUSKS",
  CREATE_TASK = "CREATE_TASK",
  FETCH_TASKS = "FETCH_TASKS",
  DROP_TASKS = "DROP_TASKS",
  CHANGE_STATUS_TASK = "CHANGE_STATUS_TASK",
  GET_TASKS_BY_NAME = "GET_TASKS_BY_NAME",
  SET_TASKS_BY_NAME = "SET_TASKS_BY_NAME",
}
